# fly.toml app configuration file generated for emanuel-network-polished-darkness-8935 on 2025-06-15T15:54:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emanuel-network-polished-darkness-8935'
primary_region = 'waw'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'emanuel-network-polished-darkness-8935.fly.dev'
  PORT = '8080'

[[mounts]]
  source = 'uploads_data'
  destination = '/app/emanuel-network/lib/0.1.0/priv/static/uploads'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
